### ISSUE TITLE
Potential solution for Youtube Audio player

### ISSUE THREAD

**Issue by randallbcotter** [FaithFamilyChurch/sundaypro_DEPRECATED#5]
https://github.com/JemiloII/Youtube-Audio-Player

**Comment by randallbcotter** [comment]
Another potential component:
https://zenplayer.audio/?v=NakTy2LQUes

**Comment by musicmunky** [comment]
Here's the github repo for the Zenplayer:  [link](https://github.com/zen-audio-player/zen-audio-player.github.io)

**Comment by musicmunky** [comment]
This issue was moved to FaithFamilyChurch/serviceable#5
