### ISSUE TITLE
Favorite notification plugin found

### ISSUE THREAD

**Issue by randallbcotter** [FaithFamilyChurch/sundaypro_DEPRECATED#6]
I really like this notification plugin. I'd only make a couple CSS changes for minor stuff. 
http://codeseven.github.io/toastr/demo.html
<img src="http://johnpapa.net/wp-content/images/toastr-icon.png">
Toastr

**Comment by musicmunky** [comment]
This issue was moved to FaithFamilyChurch/serviceable#6
